-- Historical no-op migration.
--
-- This migration originally re-pointed seeded demo reports' owner_login from a
-- maintainer handle to the repo URL namespace. Those fabricated demo rows have
-- been removed: the seed (supabase/seed.sql) now inserts only REAL famous-repo
-- scans whose owner_login already equals the GitHub owner, so no re-pointing is
-- needed. The original UPDATEs were guarded by the old fake handles, making them
-- no-ops once the fake rows are gone.
--
-- Kept as an empty, valid migration so the migration history is not rewritten
-- (already-applied environments stay consistent). New environments seed the
-- correct owner_login directly.
select 1;
